name: Full CI/CD for Streamlit

on:
  push:
    branches: ["main"]

jobs: 
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps: 
      - uses: actions/checkout@v4 
      - name: Setup Python 
        uses: actions/setup-python@v3
        with: 
          python-version: ${{matrix.python-version}}
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt 

  deploy:
    name: Deploying to EC2 
    runs-on: ubuntu-latest
    needs: 
      - build 
    steps:
      - uses: actions/checkout@v4 
      
      - name: Pulling on the Server
        uses: easingthemes/ssh-deploy@main 
        env: 
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: /home/ubuntu/web_app
        
      - name: Installing Packages
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: | 
            sudo apt update
            sudo apt install -y python3-pip python3-venv
          
      - name: Run Streamlit App
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
           cd /home/ubuntu/web_app
           python3 -m venv venv
           source venv/bin/activate 
           pip install --upgrade pip 
           pip install -r requirements.txt 
           nohup streamlit run /home/ubuntu/web_app/app.py --server.port 8501 > /dev/null 2>&1 & 
    
        
      









        
